version: "3"

services:
  exercise2-8-frontend:
    image: frontend
    build: .
    environment:
      - API_URL=http://localhost:8000
    ports:
      - 5000:5000
  exercise2-8-backend:
    image: backend
    build: .
    ports:
      - 8000:8000
    environment:
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
      - DB_USERNAME=kalle
      - DB_PASSWORD=kikkeli
      - DB_HOST=postgres
    restart: unless-stopped
  redis:
    image: redis
    build: .
  postgres:
    image: postgres
    build: .
    environment:
      - POSTGRES_USER=kalle
      - POSTGRES_PASSWORD=kikkeli
  nginx:
    image: nginx
    build: .
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
