version: "3"

services:
  exercise3-1-frontend:
    image: frontend-optimized
    build: .
    environment:
      - API_URL=http://localhost:8000
    ports:
      - 5000:5000
  exercise3-1-backend:
    image: backend-optimized
    build: .
    environment:
      - FRONT_URL=http://localhost:5000
    ports:
      - 8000:8000
