version: "3"

services:
  exercise2-5-frontend:
    image: frontend
    build: .
    ports:
      - 5000:5000
  exercise2-5-backend:
    image: backend
    build: .
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
    restart: unless-stopped
  redis:
    image: redis
    build: .
